"""Main snakefile for polygeic risk score"""

include: "const.py"
include: "sf_manifest.py"
include: "sf_filter.py"
include: "sf_prep.py"
include: "sf_qc.py"
include: "sf_hapmap.py"
include: "sf_mds.py"
include: "sf_prs.py"
